url: "//alterego.clothing"
highlighter: pygments

# Permalinks
permalink: pretty

# Server
baseurl: /
encoding: UTF-8

languages: ['en', 'id', 'zh']
languages_text: ['English', 'Bahasa Indonesia', '中文']
language_default: 'en'

exclude_from_localizations: ['Gemfile', 'Gemfile.lock', 'CNAME', 'robots.txt', 'js', 'images', 'css', 'assets']

languages_locale:
  en: "English"
  id: "Indonesia"
  zh: "Chinese"

analytics:
  google:
    account: UA-43024238-2
    domain: "alterego.clothing"

gems:
  - jekyll-sitemap